name: Fetch and preprocess data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  fetch_and_preprocess:
    name: Fetch and preprocess all data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install uv
        run: |
          pipx install uv

      # ✅ INSTALL DVC
      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: DVC setup remote
        # ✅ AUTHENTICATE TO AWS S3
        run: |
          uv run dvc remote modify origin --local access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          uv run dvc remote modify origin --local secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run DVC pipeline
        run: |
          uv run dvc pull
          uv run dvc status
          uv run dvc repro
          uv run dvc push
          git add dvc.lock
          git commit -m "Updated dvc.lock on `date` with GitHub Actions" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}